#!/usr/bin/env python3
"""
Fix smashed-together titles in releases.json by splitting words.
Uses full-title overrides + per-word overrides.
"""

import json
import re
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
RELEASES_FILE = DATA_DIR / "releases.json"

# ── Full title overrides (raw title → fixed) ────────────────────────
FULL_TITLE = {
    "blaktony wearedtroit therogue": "Blak Tony / We Are Dtroit / The Rogue",
    "moritzvonoswald borderland": "Moritz Von Oswald / Borderland",
    "anttirannisto cd": "Antti Rannisto",
    "staffanlinzatti murphyprophetofregret": "Staffan Linzatti / Murphy Prophet Of Regret",
    "subtractivesynthesisvii strikebynight": "Subtractive Synthesis VII / Strike By Night",
    "silentservant historysurvivors": "Silent Servant / History Survivors",
    "hyperactive trusttheprocess": "Hyperactive / Trust The Process",
    "presents emeraldcity musicforthephysicaltheatre": "Presents Emerald City / Music For The Physical Theatre",
    "presents westofdetroit": "Presents West Of Detroit",
    "shufflemaster specularhallucination": "Shufflemaster / Specular Hallucination",
    "thedevilscurators volume3": "The Devils Curators Vol. 3",
    "unknownlandscapes selected6": "Unknown Landscapes / Selected 6",
    "sleeparchive charltonarchives": "Sleep Archive / Charlton Archives",
    "heartofwaveform waveformtransmission": "Heart Of Waveform / Waveform Transmission",
    "theunknown steringthelight": "The Unknown / Steering The Light",
    "untitled tracks": "Untitled Tracks",
    "ritonarchi diesel": "Riton Archi Diesel",
    "therainbow forgotten": "The Rainbow / Forgotten",
    "hablame amistadmodelo": "Hablame / Amistad Modelo",
    "meets andreasgehm": "Meets Andreas Gehm",
    "meets exium regenerativecircuits part1": "Meets Exium / Regenerative Circuits Pt. 1",
    "hardmatter warmcurrents": "Hard Matter / Warm Currents",
    "billyturner parallelseries6": "Billy Turner / Parallel Series 6",
    "jeffrushin parallelseries5": "Jeff Rushin / Parallel Series 5",
    "silentservant pyecorneraudio issuetwentytwo": "Silent Servant / Pye Corner Audio / Issue Twenty Two",
    "drexciya4 theunknownaquazone yourenowenteringthebasaltzone": "Drexciya 4 / The Unknown Aqua Zone / You're Now Entering The Basalt Zone",
    "drexciya4 theunknownaquazone yourenowenteringthefusionzone": "Drexciya 4 / The Unknown Aqua Zone / You're Now Entering The Fusion Zone",
    "brendonmoeller theanatomyofthought": "Brendon Moeller / The Anatomy Of Thought",
    "terrencedixon thecollective": "Terrence Dixon / The Collective",
    "theadvent gravitywontholdme": "The Advent / Gravity Won't Hold Me",
    "theartofteknotika tigertrance": "The Art Of Teknotika / Tiger Trance",
    "surgeon scoundrel": "Surgeon Scoundrel",
    "chillygonzales consumedinkey": "Chilly Gonzales / Consumed In Key",
    "colinbenders 22clnbndrsxspdj": "Colin Benders / 22CLNBNDRS x SPDJ",
    "donatodozzy excavations": "Donato Dozzy / Excavations",
    "djshufflemaster beatboxx remixes": "DJ Shufflemaster / Beatboxx Remixes",
    "ericcloutier palinoialtd001": "Eric Cloutier / Palinoia Ltd 001",
    "alexanderkowalski muzzleblast": "Alexander Kowalski / Muzzle Blast",
    "alpha thefamily": "Alpha / The Family",
    "concentrate focus": "Concentrate / Focus",
    "efdemin phantasma volume1": "Efdemin / Phantasma Vol. 1",
    "jamesruskin soundpressure": "James Ruskin / Sound Pressure",
    "mikeschommer submerged": "Mike Schommer / Submerged",
    "stinginginsects stagesofmetals": "Stinging Insects / Stages Of Metals",
    "asbestos sleeparchive": "Asbestos / Sleep Archive",
    "lostrecordings2 howcanweknow redefined": "Lost Recordings 2 / How Can We Know / Redefined",
    "lostrecordings7 inchoateform": "Lost Recordings 7 / Inchoate Form",
    "lostrecordings8 transcendence": "Lost Recordings 8 / Transcendence",
    "plastique01 seasonedgreetings": "Plastique 01 / Seasoned Greetings",
    "paulmac elements rolledoutandback": "Paul Mac / Elements / Rolled Out And Back",
    "paulmac nervousenergy": "Paul Mac / Nervous Energy",
    "pearl aboveustoday": "Pearl / Above Us Today",
    "woodymcbride basketballheroes2": "Woody McBride / Basketball Heroes 2",
    "function covertoperations": "Function / Covert Operations",
    "eddymasvoodler talleric": "Eddy Mas Voodler / Tall Eric",
    "desroi inmirrors": "Desroi / In Mirrors",
    "aands theorderofoccurrence": "A&S / The Order Of Occurrence",
    "cirkle metamora": "Cirkle / Metamora",
    "disciplina mitologem": "Disciplina / Mitologem",
    "skreelah nemec": "Skreelah / Nemec",
    "ekmoah zylacanth": "Ekmoah / Zylacanth",
    "vainqueur surace immersion": "Vainqueur / Surace / Immersion",
    "vs alexcortex soliton nullphysics": "Vs Alex Cortex / Soliton / Null Physics",
    "vs kononon1 misikuludub": "Vs Kononon 1 / Misikulu Dub",
    "vs spacedjz catharsis": "Vs Space DJZ / Catharsis",
    "sonituseco editselect": "Sonitus Eco / Edit Select",
    "gameone thinkquick": "Game One / Think Quick",
    "tobias zahlenraum": "Tobias / Zahlenraum",
    "ohm sameining": "Ohm / Sameining",
    "5yearscompilation partfive": "5 Years Compilation Pt. 5",
    "5yearsofartefacts chapterone": "5 Years Of Artefacts / Chapter One",
    "tracksmodes3 industrialstructures": "Tracks Modes 3 / Industrial Structures",
    "mccarthy somanylies": "McCarthy / So Many Lies",
    "matrixxman strapped": "Matrixxman / Strapped",
    "vilna hagagatan": "Vilna / Hagagatan",
    "joemanu dreamlife": "Joe Manu / Dreamlife",
    "timtaylor untitled": "Tim Taylor / Untitled",
    "translate amtk005": "Translate / AMTK005",
    "presents echospace thecoldestseason1": "Presents Echospace / The Coldest Season 1",
    "speedyj 6rdhdxspdj": "Speedy J / 6RDHDXSPDJ",
    "svreca skirt untitled": "Svreca / Skirt / Untitled",
    "setaocmass isolate": "Setaoc Mass / Isolate",
    "arrival part1": "Arrival Pt. 1",
    "dopplershift part1": "Doppler Shift Pt. 1",
    "vertigo part1": "Vertigo Pt. 1",
    "diefaser partone": "Die Faser Pt. 1",
    "floorshow partii": "Floor Show Pt. 2",
    "perceptionseries partii": "Perception Series Pt. 2",
    "secretchapter parti": "Secret Chapter Pt. 1",
    "moveableparts chapter1": "Moveable Parts Ch. 1",
    "subtractivesynthesis volume1": "Subtractive Synthesis Vol. 1",
    "inversions vol2": "Inversions Vol. 2",
    "waveformtransmission volume1": "Waveform Transmission Vol. 1",
    "love remixes": "Love / Remixes",
    "work remixes": "Work / Remixes",
    "seemiyah remixes4": "See Mi Yah / Remixes 4",
    "stanislavtolkachev 220": "Stanislav Tolkachev / 220",
    "stanislavtolkachev inkblots1": "Stanislav Tolkachev / Inkblots 1",
    "stanislavtolkachev toinenruno": "Stanislav Tolkachev / Toinen Runo",
    "moveablepartschapter2": "Moveable Parts Ch. 2",
    "process12": "Process 12",
    "myonneutrino zboson": "Myon Neutrino / Z Boson",
    "n batteredfromthefall": "N / Battered From The Fall",
    "decka crossedwires": "Decka / Crossed Wires",
    "washere cd": "Was Here",
    "roberthood moveablepartschapter2": "Robert Hood / Moveable Parts Ch. 2",
    "donatodozzy brandolupi": "Donato Dozzy / Brand Olupi",
}

# ── Per-word overrides (smashed word → split) ───────────────────────
WORD_MAP = {
    "infophysix": "Infophysix",
    "theanalogsessionsofdarkness": "The Analog Sessions Of Darkness",
    "divineritual": "Divine Ritual",
    "basictonalremake": "Basic Tonal Remake",
    "dwellerofdarkness": "Dweller Of Darkness",
    "elimperiodelosdeseos": "El Imperio De Los Deseos",
    "flautosynthetico": "Flauto Synthetico",
    "nohatsrequired": "No Hats Required",
    "everythingisruined": "Everything Is Ruined",
    "wesaidnoallies": "We Said No Allies",
    "livefromsomewhere": "Live From Somewhere",
    "allnightvigil": "All Night Vigil",
    "thealtamirian": "The Altamirian",
    "whenstarsremember": "When Stars Remember",
    "thereturnofdrexciya": "The Return Of Drexciya",
    "haziestjustbeforethedawn": "Haziest Just Before The Dawn",
    "becomenothing": "Become Nothing",
    "spatialsequencesynesthesia": "Spatial Sequence Synesthesia",
    "instockholmwedwell": "In Stockholm We Dwell",
    "themasterside": "The Master Side",
    "regenerativecircuits": "Regenerative Circuits",
    "deepseadweller": "Deep Sea Dweller",
    "actioreactio": "Actio Reactio",
    "analoguebubblebath": "Analogue Bubblebath",
    "blackpropaganda": "Black Propaganda",
    "takemysoul": "Take My Soul",
    "heartofwaveform": "Heart Of Waveform",
    "theunknownaquazone": "The Unknown Aqua Zone",
    "thedielectriccoefficient": "The Dielectric Coefficient",
    "crossroads": "Crossroads",
    "theartofteknotika": "The Art Of Teknotika",
    "allkillernofiller": "All Killer No Filler",
    "ibarebecauseyoudo": "I Bare Because You Do",
    "thepentakislopes": "The Pentaki Slopes",
    "thestartitup": "The Start It Up",
    "toolssketches": "Tools / Sketches",
    "norepressbutwarehousefind": "No Repress But Warehouse Find",
    "ratherthandeep": "Rather Than Deep",
    "backtotheraw": "Back To The Raw",
    "lovesexacid": "Love Sex Acid",
    "stompthebeat": "Stomp The Beat",
    "singlikeabird": "Sing Like A Bird",
    "seasonedgreetings": "Seasoned Greetings",
    "trainofthought": "Train Of Thought",
    "stateofmind": "State Of Mind",
    "nomorewords": "No More Words",
    "justcloseyoureyes": "Just Close Your Eyes",
    "teensonfire": "Teens On Fire",
    "itwillbetoolatethen": "It Will Be Too Late Then",
    "kindledflame": "Kindled Flame",
    "thoughtcontrol": "Thought Control",
    "deadclocking": "Dead Clocking",
    "stagesofmetals": "Stages Of Metals",
    "feedforward": "Feed Forward",
    "rawfromanger": "Raw From Anger",
    "truestories": "True Stories",
    "primaryevidence": "Primary Evidence",
    "physicalplant": "Physical Plant",
    "flamesaround": "Flames Around",
    "globalwarning": "Global Warning",
    "crossedwires": "Crossed Wires",
    "crossedpaths": "Crossed Paths",
    "bittermusic": "Bitter Music",
    "sacredground": "Sacred Ground",
    "soundpressure": "Sound Pressure",
    "nervousenergy": "Nervous Energy",
    "naturalcauses": "Natural Causes",
    "secretchapter": "Secret Chapter",
    "modernheads": "Modern Heads",
    "formandvoid": "Form And Void",
    "timeandspace": "Time And Space",
    "transcendence": "Transcendence",
    "deprivation": "Deprivation",
    "concentrate": "Concentrate",
    "dissertation": "Dissertation",
    "coalescence": "Coalescence",
    "regeneration": "Regeneration",
    "applications": "Applications",
    "excavations": "Excavations",
    "infraredglow": "Infrared Glow",
    "hidingknives": "Hiding Knives",
    "muzzleblast": "Muzzle Blast",
    "angelplague": "Angel Plague",
    "tigertrance": "Tiger Trance",
    "playerhater": "Player Hater",
    "weavingshadows": "Weaving Shadows",
    "moveableparts": "Moveable Parts",
    "quadrantdub": "Quadrant Dub",
    "pralinehorse": "Praline Horse",
    "dopplershift": "Doppler Shift",
    "noveltywaves": "Novelty Waves",
    "homegrowndubs": "Home Grown Dubs",
    "magnetfluss": "Magnet Fluss",
    "holzrhythmus": "Holz Rhythmus",
    "nullphysics": "Null Physics",
    "theobserver": "The Observer",
    "skitzofrantic": "Skitzo Frantic",
    "jetsetlovelife": "Jet Set Love Life",
    "championsbreakfast": "Champions Breakfast",
    "blandambition": "Bland Ambition",
    "ashellofspeed": "A Shell Of Speed",
    "filolovestheacid": "Filo Loves The Acid",
    "liveatmaxxi": "Live At MAXXI",
    "liveindetroit": "Live In Detroit",
    "firstcontact": "First Contact",
    "emergingera": "Emerging Era",
    "futurenights": "Future Nights",
    "fastsequence": "Fast Sequence",
    "eternalrestriction": "Eternal Restriction",
    "doremifasola": "Do Re Mi Fa So La",
    "facethenation": "Face The Nation",
    "humanelements": "Human Elements",
    "humanpattern": "Human Pattern",
    "symboliclanguage": "Symbolic Language",
    "uselesschain": "Useless Chain",
    "tworecordings": "Two Recordings",
    "vertebraewaltz": "Vertebrae Waltz",
    "lastmanstanding": "Last Man Standing",
    "wearebandits": "We Are Bandits",
    "mistakenidentity": "Mistaken Identity",
    "tradebeliefs": "Trade Beliefs",
    "urbanpenetration": "Urban Penetration",
    "inchoateform": "Inchoate Form",
    "spectralnomad": "Spectral Nomad",
    "stinginginsects": "Stinging Insects",
    "backwardsman": "Backwards Man",
    "lookinginward": "Looking Inward",
    "negativefascination": "Negative Fascination",
    "truncheoncadence": "Truncheon Cadence",
    "computermadness": "Computer Madness",
    "showmethatlight": "Show Me That Light",
    "theeyesthemselves": "The Eyes Themselves",
    "thefallofbecause": "The Fall Of Because",
    "thebalanceofpower": "The Balance Of Power",
    "thecollective": "The Collective",
    "thelabyrinth": "The Labyrinth",
    "theextremist": "The Extremist",
    "thepatpricecase": "The Pat Price Case",
    "theorderofoccurrence": "The Order Of Occurrence",
    "themartianmystique": "The Martian Mystique",
    "thebloodofourking": "The Blood Of Our King",
    "theproteinvalve": "The Protein Valve",
    "theartofwar": "The Art Of War",
    "theanatomyofthought": "The Anatomy Of Thought",
    "howcanweknow": "How Can We Know",
    "walkalongthebottom": "Walk Along The Bottom",
    "wheretherainbowbegins": "Where The Rainbow Begins",
    "bendyourears": "Bend Your Ears",
    "callitwhatyouwant": "Call It What You Want",
    "swingtheclub": "Swing The Club",
    "justaskthelonely": "Just Ask The Lonely",
    "beyondthebounds": "Beyond The Bounds",
    "fromtheashes": "From The Ashes",
    "rolledoutandback": "Rolled Out And Back",
    "confessionreversion": "Confession Reversion",
    "slowdownbasterd": "Slow Down Basterd",
    "parallelperception": "Parallel Perception",
    "retelevised": "Re-Televised",
    "myonneutrino": "Myon Neutrino",
    "constitutionofsound": "Constitution Of Sound",
    "oktoberfest": "Oktoberfest",
    "posttraumaticson": "Post Traumatic Son",
    "specialedition": "Special Edition",
    "basicreshape": "Basic Reshape",
    "diagnosticcheck": "Diagnostic Check",
    "knobsandswitches": "Knobs And Switches",
    "backwardimprovement": "Backward Improvement",
    "lastthreemounts": "Last Three Mounts",
    "winterinkalamazoo": "Winter In Kalamazoo",
    "overduenotification": "Overdue Notification",
    "batteredfromthefall": "Battered From The Fall",
    "upthesteelstairway": "Up The Steel Stairway",
    "cosmicdistancemarkers": "Cosmic Distance Markers",
    "nanoscopicscales": "Nanoscopic Scales",
    "hydrostaticequilibrium": "Hydrostatic Equilibrium",
    "functionofaconstant": "Function Of A Constant",
    "gravitywontholdme": "Gravity Won't Hold Me",
    "publicconsciousness": "Public Consciousness",
    "systematicadvancing": "Systematic Advancing",
    "classifyasunclassified": "Classify As Unclassified",
    "toostupidtobeanxious": "Too Stupid To Be Anxious",
    "anyotherstyles": "Any Other Styles",
    "iamapathyiamsubmission": "I Am Apathy I Am Submission",
    "perceptionseries": "Perception Series",
    "learningtobeamachine": "Learning To Be A Machine",
    "bubblemetropolis": "Bubble Metropolis",
    "cosmopolitanforthecosmos": "Cosmopolitan For The Cosmos",
    "consumedinkey": "Consumed In Key",
    "maintainthegoldenratio": "Maintain The Golden Ratio",
    "covertoperations": "Covert Operations",
    "hangarsdorion": "Hangars D'Orion",
    "compuercontrolled": "Computer Controlled",
    "imperialpropaganda": "Imperial Propaganda",
    "severalstreamsofthought": "Several Streams Of Thought",
    "updatingtheexistingsystems": "Updating The Existing Systems",
    "evilplanete": "Evil Planete",
    "inasyriantongue": "In A Syrian Tongue",
    "twosidestoeverystory": "Two Sides To Every Story",
    "everythingindarknesscomestolight": "Everything In Darkness Comes To Light",
    "nocturbulousbehavior": "Nocturbulous Behavior",
    "thesearedreamsandthereisescape": "These Are Dreams And There Is Escape",
    "tilllovedouspart": "Till Love Do Us Part",
    "amandiesinthestreet": "A Man Dies In The Street",
    "unknownfreakquencies": "Unknown Freakquencies",
    "aquaticinvasion": "Aquatic Invasion",
    "whystennyalwayslyingme": "Why Stenny Always Lying Me",
    "noonecanhearyourechoinspace": "No One Can Hear Your Echo In Space",
    "noonesdriving": "No One's Driving",
    "nothingproducesstarkimagery": "Nothing Produces Stark Imagery",
    "otherskillcallsandfuture": "Other Skill Calls And Future",
    "deliveredintothehandsofindifference": "Delivered Into The Hands Of Indifference",
    "youfoundoutitgoesbacktoendlessreality": "You Found Out It Goes Back To Endless Reality",
    "yourenowenteringthebasaltzone": "You're Now Entering The Basalt Zone",
    "yourenowenteringthefusionzone": "You're Now Entering The Fusion Zone",
    "afancyhaircutwillnothelpyoutomakebettertracks": "A Fancy Haircut Will Not Help You To Make Better Tracks",
    "atrackisatrackisatrack": "A Track Is A Track Is A Track",
    "echoesoffancientlife": "Echoes Of Ancient Life",
    "brothersinmind": "Brothers In Mind",
    "alwaysoffendedneverashamed": "Always Offended Never Ashamed",
    "handsofglory": "Hands Of Glory",
    "issuetwentytwo": "Issue Twenty Two",
    "stocktowncity": "Stocktown City",
    "shinjukumad": "Shinjuku Mad",
    "terzogiorno": "Terzo Giorno",
    "simmetriadellestringhe": "Simmetria Delle Stringhe",
    "amistadmodelo": "Amistad Modelo",
    "lunemexundogroundsoundtrack": "Lunemex Underground Soundtrack",
    "soulsurvivor": "Soul Survivor",
    "misikuludub": "Misikulu Dub",
    "aboveustoday": "Above Us Today",
    "greatspacesoaster": "Great Space Coaster",
    "slovakiannightsremixed": "Slovakian Nights Remixed",
    "elektroniquedweller": "Electronique Dweller",
    "elektroniquedwellerremixes": "Electronique Dweller Remixes",
    "acidpinupsii": "Acid Pinups II",
    "acidtracks": "Acid Tracks",
    "acidsketch": "Acid Sketch",
    "activeline": "Active Line",
    "adrianalopez": "Adriana Lopez",
    "albertvanabbe": "Albert Van Abbe",
    "alexanderkowalski": "Alexander Kowalski",
    "alldaylong": "All Day Long",
    "andreasgehm": "Andreas Gehm",
    "angelgate": "Angel Gate",
    "annabeate": "Anna Beate",
    "anotherone": "Another One",
    "assemblercode": "Assembler Code",
    "atomitron": "Atomitron",
    "asymptote": "Asymptote",
    "beatboxx": "Beatboxx",
    "billyturner": "Billy Turner",
    "bleepazoid": "Bleepazoid",
    "brendonmoeller": "Brendon Moeller",
    "brandolupi": "Brand Olupi",
    "britishmurderboys": "British Murder Boys",
    "casualcare": "Casual Care",
    "charltonarchives": "Charlton Archives",
    "chesterbeatty": "Chester Beatty",
    "chillygonzales": "Chilly Gonzales",
    "colinbenders": "Colin Benders",
    "contrasto": "Contrasto",
    "convextion": "Convextion",
    "coryarcane": "Cory Arcane",
    "darkmatter": "Dark Matter",
    "dbgiiproject": "DBG II Project",
    "demonintheattic": "Demon In The Attic",
    "dimensions": "Dimensions",
    "djshufflemaster": "DJ Shufflemaster",
    "donatodozzy": "Donato Dozzy",
    "downtownworlds": "Downtown Worlds",
    "eddymasvoodler": "Eddy Mas Voodler",
    "eldiablo": "El Diablo",
    "ericcloutier": "Eric Cloutier",
    "exotika": "Exotika",
    "facilities": "Facilities",
    "fatpunko": "Fat Punko",
    "figurespcv": "Figures PCV",
    "firsttrip": "First Trip",
    "fourorgans": "Four Organs",
    "frenchkiss": "French Kiss",
    "frontier": "Frontier",
    "groundhog": "Groundhog",
    "groundloop": "Groundloop",
    "humanoid": "Humanoid",
    "huyendo": "Huyendo",
    "hybridi": "Hybridi",
    "iceplanet": "Ice Planet",
    "ifachcollective": "Ifach Collective",
    "iftango": "If Tango",
    "illmatic": "Illmatic",
    "imbecile": "Imbecile",
    "incubation": "Incubation",
    "industry": "Industry",
    "infidentity": "Infidentity",
    "inmemoriam": "In Memoriam",
    "innerlife": "Inner Life",
    "inpureform": "In Pure Form",
    "industrialstructures": "Industrial Structures",
    "inversions": "Inversions",
    "invincible": "Invincible",
    "iwasnomind": "I Was No Mind",
    "jamesruskin": "James Ruskin",
    "jeroensearch": "Jeroen Search",
    "kimbilir": "Kim Bilir",
    "klankman": "Klankman",
    "kronotop": "Kronotop",
    "leterrible": "Le Terrible",
    "lifelike": "Lifelike",
    "lioninmars": "Lion In Mars",
    "lowdown": "Lowdown",
    "magenta": "Magenta",
    "metaphor": "Metaphor",
    "metrical": "Metrical",
    "mikeparker": "Mike Parker",
    "mikeschommer": "Mike Schommer",
    "mingusahum": "Mingus Ah Um",
    "minimalism": "Minimalism",
    "mitologem": "Mitologem",
    "moonstruck": "Moonstruck",
    "montreal": "Montreal",
    "mufflerman": "Muffler Man",
    "musicofthespehers": "Music Of The Spheres",
    "mutedicons": "Muted Icons",
    "newironage": "New Iron Age",
    "nightfever": "Nightfever",
    "normalre": "Normal Re",
    "northbound": "Northbound",
    "nullity": "Nullity",
    "objective": "Objective",
    "oliverrosemann": "Oliver Rosemann",
    "omnitronic": "Omnitronic",
    "overand": "Over And",
    "painkiller": "Painkiller",
    "panasonic": "Panasonic",
    "patterns": "Patterns",
    "pelotone": "Pelotone",
    "plantae": "Plantae",
    "pointblank": "Point Blank",
    "presence": "Presence",
    "presents": "Presents",
    "preview": "Preview",
    "process": "Process",
    "prospect": "Prospect",
    "pruittigoe": "Pruitt Igoe",
    "psykofuk": "Psykofuk",
    "radiant": "Radiant",
    "rawmini": "Raw Mini",
    "recycle": "Recycle",
    "redrising": "Red Rising",
    "regiment": "Regiment",
    "relinked": "Relinked",
    "remixes": "Remixes",
    "replicant": "Replicant",
    "revolver": "Revolver",
    "reworked": "Reworked",
    "romanponcet": "Roman Poncet",
    "rudiment": "Rudiment",
    "runnings": "Runnings",
    "sanssouci": "Sans Souci",
    "secondwave": "Second Wave",
    "security": "Security",
    "shadowboat": "Shadow Boat",
    "shellwave": "Shellwave",
    "slammedown": "Slammed Own",
    "sleeparchive": "Sleep Archive",
    "slowhand": "Slowhand",
    "solarlimb": "Solar Limb",
    "sonicstate": "Sonic State",
    "sonicsurge": "Sonic Surge",
    "spacedjz": "Space DJZ",
    "spindizzy": "Spin Dizzy",
    "stanislavtolkachev": "Stanislav Tolkachev",
    "starlight": "Starlight",
    "sterastudent": "Sterac Student",
    "strgths": "STRGTHS",
    "substation": "Substation",
    "subvoiceproject": "Subvoice Project",
    "subzero": "Sub Zero",
    "sustain": "Sustain",
    "tangent": "Tangent",
    "technique": "Technique",
    "tensale": "Tensale",
    "terrencedixon": "Terrence Dixon",
    "thecalling": "The Calling",
    "thedexit": "The Dexit",
    "thenumbers": "The Numbers",
    "thequest": "The Quest",
    "theremixes": "The Remixes",
    "therhythmsofnature": "The Rhythms Of Nature",
    "thesekinkydudesfromgermany": "These Kinky Dudes From Germany",
    "thewaythroughallthings": "The Way Through All Things",
    "timaeus": "Timaeus",
    "totmacher": "Totmacher",
    "transition": "Transition",
    "transport": "Transport",
    "turinversions": "Turin Versions",
    "twingods": "Twin Gods",
    "unanimity": "Unanimity",
    "unpatterns": "Unpatterns",
    "unspoken": "Unspoken",
    "untitled": "Untitled",
    "vapours": "Vapours",
    "various": "Various",
    "victorious": "Victorious",
    "voiceprint": "Voiceprint",
    "vortekz": "Vortekz",
    "vvvllllvvv": "VVVLLLLVVV",
    "walktype": "Walktype",
    "warmcurrents": "Warm Currents",
    "palicavonzvreca": "Palica Von Zvreca",
    "woodymcbride": "Woody McBride",
    "yellowyard": "Yellow Yard",
    "pyecorneraudio": "Pye Corner Audio",
    "somanylies": "So Many Lies",
    "thinkquick": "Think Quick",
    "toinenruno": "Toinen Runo",
    "inkblots1": "Inkblots 1",
    "basketballheroes2": "Basketball Heroes 2",
    "palinoialtd001": "Palinoia Ltd 001",
    "parallelseries6": "Parallel Series 6",
    "parallelseries5": "Parallel Series 5",
    "abyssal": "Abyssal",
    "afterlife": "Afterlife",
    "armstrong": "Armstrong",
    "asayita": "Asayita",
    "balance": "Balance",
    "battery": "Battery",
    "berghain": "Berghain",
    "bynight": "By Night",
    "calcata": "Calcata",
    "carrier": "Carrier",
    "catharsis": "Catharsis",
    "darkmatter": "Dark Matter",
    "dependency": "Dependency",
    "distance": "Distance",
    "downfall": "Downfall",
    "drained": "Drained",
    "drainhum": "Drain Hum",
    "fadeout": "Fadeout",
    "forgotten": "Forgotten",
    "hablame": "Hablame",
    "katmoda": "Kat Moda",
    "partone": "Part One",
    "selected6": "Selected 6",
    "submerged": "Submerged",
    "dreamlife": "Dreamlife",
    "strapped": "Strapped",
    "redefined": "Redefined",
    "zahlenraum": "Zahlenraum",
    "sameining": "Sameining",
    "hagagatan": "Hagagatan",
    "phantasma": "Phantasma",
    "inmirrors": "In Mirrors",
    "metamora": "Metamora",
    "zylacanth": "Zylacanth",
    "immersion": "Immersion",
    "soliton": "Soliton",
    "aessentialtributetobillevansthefutureofmodaljazz": "A Essential Tribute To Bill Evans / The Future Of Modal Jazz",
    "crossinthemadmoon": "Cross In The Mad Moon",
    "fighttheapressers": "Fight The Oppressors",
    "hishesheandshe": "His He She And She",
    "ligertrance": "Liger Trance",
}


def fix_title(raw_title):
    """Fix a title: try full match first, then per-word."""
    low = raw_title.lower().strip()

    # Full title override
    if low in FULL_TITLE:
        return FULL_TITLE[low]

    # Per-word fixing
    words = raw_title.split()
    fixed = []
    for w in words:
        wl = w.lower()
        if wl in WORD_MAP:
            fixed.append(WORD_MAP[wl])
        elif w.isalpha() and w == w.lower() and len(w) > 1:
            fixed.append(w.title())
        else:
            fixed.append(w)

    return " ".join(fixed)


def main():
    with open(RELEASES_FILE) as f:
        data = json.load(f)

    changes = 0
    for r in data["releases"]:
        old = r["title"]
        r["title"] = fix_title(old)
        if r["title"] != old:
            changes += 1

    with open(RELEASES_FILE, "w") as f:
        json.dump(data, f, indent=2)

    print(f"Fixed {changes} titles out of {len(data['releases'])}")


if __name__ == "__main__":
    main()
